- name: Create a folder in the user's home directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/shares"
    state: directory
    mode: '0755'  # Optional: permissions for the directory

- name: Create a script file
  ansible.builtin.copy:
    dest: "/usr/local/bin/mount-vmshare"
    content: |
      #!/bin/bash
      /usr/bin/vmhgfs-fuse .host:/ {{ ansible_env.HOME }}/shares -o subtype=vmhgfs-fuse,allow_other
    mode: '0755'  # Gives execute permissions to the script
  become: true
  become_method: sudo 

