---
- block:
    - name: Install dependencies for Volatility
      apt:
        name:
          - build-essential
          - git
          - libdistorm3-dev
          - yara
          - libraw1394-11
          - libcapstone-dev
          - capstone-tool
          - tzdata
        state: present

    - name: Install Python 2 and related packages
      apt:
        name:
          - python2
          - python2.7-dev
          - libpython2-dev
        state: present

    - name: Download get-pip.py for Python 2
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip for Python 2
      command:
        cmd: python2 /tmp/get-pip.py
        creates: /usr/local/bin/pip2

    - name: Install setuptools and wheel for Python 2
      pip:
        name: 
          - setuptools
          - wheel
        state: latest
        executable: pip2

    - name: Install Python 2 dependencies for Volatility 2
      pip:
        name: 
          - distorm3
          - yara
          - pycrypto
          - pillow
          - openpyxl
          - ujson
          - pytz
          - ipython
          - capstone
        state: latest
        executable: pip2

    - name: Install Volatility 2
      pip:
        name: git+https://github.com/volatilityfoundation/volatility.git
        state: latest
        executable: pip2

    - name: Install Python 3 and related packages
      apt:
        name:
          - python3
          - python3-dev
          - libpython3-dev
          - python3-pip
          - python3-setuptools
          - python3-wheel
        state: present

    - name: Install Python 3 dependencies for Volatility 3
      pip:
        name: 
          - distorm3
          - yara
          - pycryptodome
          - pillow
          - openpyxl
          - ujson
          - pytz
          - ipython
          - capstone
        state: latest
        extra_args: --ignore-installed
        executable: pip3

    - name: Install Volatility 3
      pip:
        name: git+https://github.com/volatilityfoundation/volatility3.git
        state: latest
        executable: pip3

  become: yes

