---
- name: Kali Linux Build
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - group_vars/all.yml

  roles:
    - tools
    - terminal
    - browser
    - system
    - tmux
    - xrdp
    - role: gantsign.visual-studio-code
      become: false
      vars:
        users:
          - username: "{{ username }}"
            visual_studio_code_extensions: "{{ vscode_extensions }}"
