---
- name: Kali Linux Build
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - group_vars/all.yml

  roles:
    - tools
    - terminal
    - browser
    - system
    - tmux
    - xrdp
    - vscode
