---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/customise-terminal"
    - role: "roles/customise-browser"
    - role: "roles/configure-system"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - snyk-security.snyk-vulnerability-scanner
