---
- name: Configure passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  when: username != "root"

