---
- name: Copy Burp CA extraction script
  ansible.builtin.copy:
    src: getburpcert.sh
    dest: /usr/local/bin/getburpcert.sh
    mode: "0755"

- name: Create BurpSuite lib directory
  ansible.builtin.file:
    path: /usr/local/lib/BurpSuite
    state: directory
    mode: "0755"

- name: Check if Burp Suite extras exist
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  loop: "{{ burp_extras }}"
  register: burp_extras_stat

- name: Download Burp Suite extras
  ansible.builtin.get_url:
    url: "{{ item.item.url }}"
    dest: "{{ item.item.dest }}"
    mode: "0644"
  loop: "{{ burp_extras_stat.results }}"
  when: not item.stat.exists

- name: Create BurpSuite config directory
  ansible.builtin.file:
    path: "{{ home_dir }}/.BurpSuite"
    state: directory
    owner: "{{ username }}"
    mode: "0755"

- name: Deploy Burp Suite Community config
  ansible.builtin.template:
    src: UserConfigCommunity.json.j2
    dest: "{{ home_dir }}/.BurpSuite/UserConfigCommunity.json"
    owner: "{{ username }}"
    mode: "0644"
