---
- name: Create BloodHound CE directory
  ansible.builtin.file:
    path: /opt/bloodhound-ce
    state: directory
    mode: "0755"

- name: Download BloodHound CE docker-compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/SpecterOps/BloodHound/main/examples/docker-compose/docker-compose.yml
    dest: /opt/bloodhound-ce/docker-compose.yml
    mode: "0644"

- name: Pull BloodHound CE containers
  ansible.builtin.command:
    cmd: docker compose pull
    chdir: /opt/bloodhound-ce
  changed_when: true
