---
- name: Install APT packages
  ansible.builtin.include_tasks: apt.yml

- name: Install Docker CE
  ansible.builtin.include_tasks: docker.yml

- name: Download GitHub releases
  ansible.builtin.include_tasks: github-repos.yml

- name: Install Kerbrute
  ansible.builtin.include_tasks: kerbrute.yml

- name: Install Obsidian
  ansible.builtin.include_tasks: obsidian.yml

- name: Install BloodHound CE
  ansible.builtin.include_tasks: bloodhound.yml

- name: Install Volatility 3
  ansible.builtin.include_tasks: volatility.yml
  when: install_volatility3

- name: Install Syncthing
  ansible.builtin.include_tasks: syncthing.yml
