---
- name: Install Volatility 3 via pipx
  community.general.pipx:
    name: volatility3
    source: "git+https://github.com/volatilityfoundation/volatility3.git"
    state: present
  when: install_volatility3
