---
# tasks file for configure-system
- name: Add NOPASSWD rule for the current user
  become: true
  lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    regexp: "{{ ansible_user_id }} ALL="
    line: "{{ item }}"
    validate: visudo -cf %s
  when: ansible_user_id != 'root'
  with_items:
    - "{{ ansible_user_id }}\tALL=(ALL) NOPASSWD:ALL"

- name: "Copy wallpaper image"
  copy:
    src: "{{ role_path }}/files/wallpaper.jpg"
    dest: "{{ ansible_env.HOME }}/.wallpaper.jpg"

- name: Set wallpaper
  shell: xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVirtual1/workspace0/last-image -s ~/.wallpaper.jpg
